/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

public static class ZipkinCoreConstants
{
  public const string CLIENT_SEND = "cs";
  public const string CLIENT_RECV = "cr";
  public const string SERVER_SEND = "ss";
  public const string SERVER_RECV = "sr";
  public const string WIRE_SEND = "ws";
  public const string WIRE_RECV = "wr";
  public const string CLIENT_ADDR = "ca";
  public const string SERVER_ADDR = "sa";
}
